### ISSUE TITLE
I propose a simpler solution

### ISSUE THREAD

**Issue by s1gnate-sync** [supechicken/crew-sudo#2]
upstart task:
```
start on started attestationd
stop on stop ui
respawn
exec /usr/bin/vshd
```

or run it manually in VT2

client cmd:
```
/usr/bin/vsh --cid=2
```

after that use sudo as usual, chmod/chown and other stuff would work too.

**Comment by supechicken** [comment]
See https://gist.github.com/supechicken/58d530210620d24eea327043b7cb9b3b?permalink_comment_id=4829098#gistcomment-4829098
